# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact for Docker
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Download artifact from Maven
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Logging in
      run: docker login ghcr.io -u lessercodes -p ${{ github.token }}

    - name: Build Docker image
      run: docker build . -t ghcr.io/lessercodes/cubix/1/homework/app:springboot

    - name: Publish Docker image
      run: docker push ghcr.io/lessercodes/cubix/1/homework/app:springboot

  verify:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Verify Docker image
      run: ./verify-image.sh
